parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

#######################
#  COMMANDS HANDLERS  #
#######################

    App\Administration\Domain\Action\RegisterChampion\RegisterChampionCommandHandler:
        arguments:
            - '@App\BuildingBlocks\Infrastructure\Doctrine\DoctrineEventStore'
        tags:
            - 'command.handler'

#######################
# COMMAND HANDLER MAP #
#######################
    BSP\CommandBus\SimpleCommandHandlerMap:
        arguments: [!tagged command.handler]

###############
# COMMAND BUS #
###############

    BSP\CommandBus\SimpleCommandBus:
        arguments:
            - '@BSP\CommandBus\SimpleCommandHandlerMap'

#######################
# SYMFONY EVENT STORE #
#######################
    App\BuildingBlocks\Infrastructure\Doctrine\DoctrineEventStore:

###################
# SYMFONY COMMAND #
###################

    App\Administration\Infrastructure\Command\TestCommand:
        arguments:
            $commandBus: '@BSP\CommandBus\SimpleCommandBus'