parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

#######################
#  COMMANDS HANDLERS  #
#######################

    App\Domain\Administration\Action\RegisterChampion\RegisterChampionCommandHandler:
        tags:
            - 'command.handler'

    App\Application\CommandBus\CommandHandlerMap:
        arguments: [!tagged command.handler]